package com.garganttua.core.workflow.aot;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.lang.annotation.Annotation;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.garganttua.core.reflection.IConstructor;
import com.garganttua.core.reflection.IField;
import com.garganttua.core.reflection.IMethod;

/**
 * End-to-end coverage for member annotations under AOT: the descriptors
 * inspected here were generated by the real annotation processor during this
 * module's test compilation, from {@link AnnotatedMembersBean}.
 *
 * <p>The field / method / constructor generators used to hardcode
 * {@code new Annotation[0]}, so a member annotation vanished as soon as a
 * descriptor existed — while the very same annotation on the enclosing type
 * survived, because {@code AOTClassSourceGenerator} sources those from the live
 * class literal. These tests read the generated {@code INSTANCE} singletons
 * directly, by name, so no {@code AOTClass} live-reflection fallback can stand
 * in for the descriptor and mask a regression.</p>
 */
@DisplayName("AOT member descriptors — the generated singletons carry the real annotations")
class MemberAnnotationAotTest {

    private static final String PACKAGE = "com.garganttua.core.workflow.aot.";

    private static Object descriptorInstance(String simpleName) throws ReflectiveOperationException {
        Class<?> descriptor = Class.forName(PACKAGE + simpleName);
        return descriptor.getField("INSTANCE").get(null);
    }

    private static String markerValue(Annotation[] annotations) {
        for (Annotation a : annotations) {
            if (a instanceof MemberMarker marker) {
                return marker.value();
            }
        }
        return null;
    }

    @Test
    void generatedFieldDescriptorCarriesTheFieldAnnotation() throws ReflectiveOperationException {
        IField field = (IField) descriptorInstance("AOTField_AnnotatedMembersBean_tag");
        assertNotNull(field);
        assertEquals("field", markerValue(field.getAnnotations()),
                "the generated field descriptor must carry @MemberMarker(\"field\")");
        assertEquals("field", markerValue(field.getDeclaredAnnotations()));
    }

    @Test
    void generatedConstructorDescriptorCarriesTheConstructorAnnotation() throws ReflectiveOperationException {
        IConstructor<?> constructor =
                (IConstructor<?>) descriptorInstance("AOTConstructor_AnnotatedMembersBean_0");
        assertNotNull(constructor);
        assertEquals("constructor", markerValue(constructor.getAnnotations()),
                "the generated constructor descriptor must carry @MemberMarker(\"constructor\")");
    }

    @Test
    void generatedMethodDescriptorCarriesTheMethodAnnotation() throws ReflectiveOperationException {
        IMethod method = (IMethod) descriptorInstance("AOTMethod_AnnotatedMembersBean_describe_0");
        assertNotNull(method);
        assertEquals("method", markerValue(method.getAnnotations()),
                "the generated method descriptor must carry @MemberMarker(\"method\")");
    }

    @Test
    void unannotatedMemberKeepsAnEmptyAnnotationArray() throws ReflectiveOperationException {
        IField field = (IField) descriptorInstance("AOTField_AnnotatedMembersBean_count");
        assertEquals(0, field.getAnnotations().length,
                "an unannotated field must not inherit another member's annotations");
    }
}
